config/routes.rb
Rails.application.routes.draw do
  get 'plants/index'

  resources :plants

  root "plants#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #get "plants", to: "plants#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frequency.rb
class Frequency < ApplicationRecord
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
	def index
		@plants = Plant.all
	end

	def show
		@plant = Plant.find(params[:id])
	end

	def new
		@plant = Plant.new
	end

	def create
		@plant = Plant.new(plant_params)

		@plant.save
		redirect_to @plant
	end

	private
		def plant_params
			params.require(:plant).permit(:name, :frequency)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WaterIt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/index.html.erb
<h1>Hello, Plant!</h1>
<%= link_to 'New Plant', new_plant_path %>
<%= image_tag "bonsai.jpg" %>

<h1>Listing plants</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Frequency</th>
  </tr>
 
  <% @plants.each do |plant| %>
    <tr>
      <td><%= plant.name %></td>
      <td><%= plant.frequency %></td>
      <td><%= link_to 'Show', plant_path(plant) %></td>
    </tr>
  <% end %>
</table>

app/views/plants/new.html.erb
<h1>New Plant</h1>
<%= form_with scope: :plant,url: plants_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
    <p>
    <%= form.label :frequency %><br>
    <%= form.text_field :frequency %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @plant.name %>
</p>
 
<p>
  <strong>Frequency:</strong>
  <%= @plant.frequency %>
</p>
<%= link_to 'Back', plants_path %>